Gopkg.lock, Gopkg.toml
Use newer version of k8s apiserver to fix EKS issue
=> Change k8s/apiserver version

cmd/handler.go, cmd/main.go, deploy/audit-crd.yaml, pkg/anchore/client.go, pkg/anchore/types.go, pkg/apis/security/v1alpha1/deepcopy.go, pkg/apis/security/v1alpha1/types.go
- Add Image digest, name, tag. ( prerequisite to solve pipeline issue 1334 )
- Add lastUpdate to image details. ( prerequisite to solve pipeline issue 1348 )
=> Extend scanlog

deploy/whitelist-crd.yaml, pkg/anchore/client.go
=> Fix scanlog missing digest at first time check

cmd/handler.go, deploy/whitelist-crd.yaml, pkg/apis/security/v1alpha1/deepcopy.go, pkg/apis/security/v1alpha1/types.go
- Add whitelist regexp check
- Add regexp spec to whitelist crd
=> Add regexp to whitelist check

cmd/handler.go
=> Fix regexp.Compile string surrounding with ^( )$

.circleci/config.yml
=> Chart release workflow

charts/anchore-policy-validator/Chart.yaml, charts/anchore-policy-validator/templates/apiservice-webhook.yaml, charts/anchore-policy-validator/values.yaml
Update `anchore-image-validator` version to 0.4.0
=> update chart to use webhook version 0.4.0

charts/anchore-policy-validator/Chart.yaml, charts/anchore-policy-validator/templates/apiservice-webhook.yaml, charts/anchore-policy-validator/templates/validator-deployment.yaml
| Bug fix?        |yes
Fix missing k8s version check in case of apiVersion.
=> Use admissionregistration.k8s.io/v1beta1 if k8s version lower than 1.16

charts/anchore-policy-validator/Chart.yaml, charts/anchore-policy-validator/templates/apiservice-webhook.yaml
| Bug fix?        |yes
Fix indentation.
=> indentation fix

charts/anchore-policy-validator/Chart.yaml, charts/anchore-policy-validator/templates/validator-deployment.yaml
| Bug fix?        |yes
If apiservice-webhook is changed, webhook pod will be restarted
=> If apiservice-webhook is changed, pod'll be restarted

charts/anchore-policy-validator/templates/default-policy-job.yaml
| Bug fix?        |yes
Fix missing job label. This label will prevent validating by the validator.
=> Fix missing job label

pkg/anchore/client.go
| Bug fix?        | yes
The validator doesn't get the image before POST it to analyze.
=> Fix anchore client

charts/anchore-policy-validator/Chart.yaml, charts/anchore-policy-validator/templates/default-policy-job.yaml, charts/anchore-policy-validator/templates/validator-deployment.yaml, charts/anchore-policy-validator/values.yaml, pkg/anchore/client.go
| New feature?    |yes
Implement an insecure flag in `anchore-image-validator` and the chart.
1. create tag `0.4.3` and push
2. create tag `anchore-policy-validator/0.5.6` and push
=> TLS insecure flag 

charts/anchore-policy-validator/README.md
=> Update chart readme

charts/anchore-policy-validator/Chart.yaml, charts/anchore-policy-validator/README.md, charts/anchore-policy-validator/templates/default-policy-configmap.yaml, charts/anchore-policy-validator/templates/default-policy-job.yaml, charts/anchore-policy-validator/values.yaml
| New feature?    |yes
| Related tickets | fixes #59 , related https://github.com/banzaicloud/pipeline/pull/3166
Add createPolicies flag and set it false by default.
Default policy creation is implemented in the Pipeline side as well.
=> Add createPolicies value and set it false by default

charts/anchore-policy-validator/Chart.yaml, charts/anchore-policy-validator/README.md, charts/anchore-policy-validator/values.yaml
=> chart: Use ghcr

Dockerfile, Dockerfile.debug, charts/anchore-policy-validator/Chart.yaml, charts/anchore-policy-validator/ci/test-values.yaml, charts/anchore-policy-validator/templates/validator-deployment.yaml, charts/anchore-policy-validator/values.yaml, go.mod
Update base image and go version
=> Update base image

cmd/config.go, cmd/main.go, go.mod, go.sum, internal/app/app.go, internal/app/config.go, internal/app/validate.go, pkg/anchore/client.go
| New feature?    |yes
- cache with ttl
- background scan in the case of whitelist
=> Feat: cache and background scan in the case of the whitelist

charts/anchore-policy-validator/Chart.yaml, charts/anchore-policy-validator/README.md, charts/anchore-policy-validator/templates/validator-deployment.yaml, charts/anchore-policy-validator/values.yaml, cmd/config.go
| New feature?    |yes
| Related tickets | #72 
set cache TTL in values
=> Chart: cacheTTL

charts/anchore-policy-validator/Chart.yaml, internal/app/validate.go, pkg/anchore/client.go
| New feature?    | yes
| Related tickets | fixes #72
In the case of the whitelisted releases, the validator skips checking images against policy.
After merged, tag chart and image-validator.
=> Skip status check

charts/anchore-policy-validator/Chart.yaml
=> Bump validator version

charts/anchore-policy-validator/Chart.yaml
=> Bump image version

go.mod, go.sum
=> fix(dep): gopkg.in/yaml.v2
